# Generated by Django 6.1 on 2026-08-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(help_text='Android version code (e.g., 2)')),
                ('version_name', models.CharField(help_text="Version string (e.g., '1.0.1')", max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('apk_file', models.FileField(help_text='Upload the .apk file here', upload_to='apks/')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Force users to update immediately')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
