# Generated by Django 6.1 on 2026-08-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manteki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manteki.application')),
            ],
        ),
    ]
