# Generated by Django 6.1 on 2026-08-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manteki', '0002_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_reference', models.CharField(help_text='Temporary: employee name/ID until Employee model is linked', max_length=100)),
                ('document_type', models.CharField(choices=[('id', 'ID Document'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
