# Generated by Django 6.1 on 2026-08-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='anomaly_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_anomaly',
            field=models.BooleanField(default=False, help_text='Flagged if gps mismatch or other issue'),
        ),
    ]
