# Generated by Django 6.1 on 2026-08-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_officer', 'HR Officer'), ('manager', 'Manager'), ('payroll_officer', 'Payroll/Finance Officer'), ('director', 'Director/Executive'), ('employee', 'Employee'), ('applicant', 'Applicant'), ('receptionist', 'Receptionist')], default='employee', max_length=32),
        ),
    ]
