# Generated by Django 6.0.8 on 2026-08-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performancereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('feedback_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
