# Generated by Django 6.1 on 2026-08-09 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month and year for this payroll run (usually first day of month)')),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nhf', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
