# Generated by Django 5.0.6 on 2026-08-12 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. "employee.exited", "user.role_changed"', max_length=100)),
                ('target_type', models.CharField(help_text='e.g. "employees.Employee"', max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable snapshot of the target at the time of the action.', max_length=255)),
                ('changes', models.JSONField(blank=True, help_text="Optional structured detail — e.g. {'from': 'active', 'to': 'exited'}.", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Who performed the action. Null if the actor account was later deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
