# Generated by Django 5.2.17 on 2026-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_date_of_birth_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Work/contact email — distinct from login username.', max_length=254, unique=True),
        ),
    ]
