# Generated by Django 6.1 on 2026-08-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Expected office latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Expected office longitude', max_digits=9, null=True),
        ),
    ]
